### ISSUE TITLE
REMOVE Laser service from EBS for May 2015

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#419]
Laser service is being retired in May 2015.  It will no longer be needed in the EBS.

Appearances of Laser

##### Before

<img width="1167" alt="screen shot 2017-02-09 at 1 00 46 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803000/e58bf478-eec7-11e6-8626-11add70da451.png">

##### After
<img width="1096" alt="screen shot 2017-02-09 at 1 21 36 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803663/ba735440-eeca-11e6-8bec-a3ba51d20929.png">

##### Before

<img width="910" alt="screen shot 2017-02-09 at 1 00 33 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803006/ed306182-eec7-11e6-995e-2a21f01c9415.png">

### After
<img width="783" alt="screen shot 2017-02-09 at 1 14 09 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803440/c639b5c2-eec9-11e6-9c5a-ad1cb3387310.png">

##### Before
<img width="1224" alt="screen shot 2017-02-09 at 1 04 33 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803231/f505958e-eec8-11e6-9a3e-7cf633ddf0a7.png">

##### After

<img width="904" alt="screen shot 2017-02-09 at 1 18 47 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803571/61856634-eeca-11e6-872e-23aa5a1db67d.png">

##### Before
<img width="991" alt="screen shot 2017-02-09 at 1 02 13 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803022/034e3282-eec8-11e6-8b14-a3e9bc553b5f.png">

<img width="537" alt="screen shot 2017-02-09 at 1 02 48 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803034/177a2888-eec8-11e6-858e-be9d6a883579.png">

##### After

<img width="761" alt="screen shot 2017-02-09 at 1 25 05 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803789/3c6da66c-eecb-11e6-9979-d036372a1b45.png">
<img width="551" alt="screen shot 2017-02-09 at 1 25 09 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803790/3c70c5f4-eecb-11e6-9546-08eb67359878.png">

##### Before
<img width="571" alt="screen shot 2017-02-09 at 1 24 08 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803752/16bbb86e-eecb-11e6-8d27-82d2f09281c6.png">

##### After

<img width="688" alt="screen shot 2017-02-09 at 1 27 56 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803882/99e060dc-eecb-11e6-8fd6-e1c612b02a18.png">

##### Before
<img width="800" alt="screen shot 2017-02-09 at 1 03 44 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803156/a4cc3b04-eec8-11e6-9c15-2599359a1810.png">

##### After
<img width="1419" alt="screen shot 2017-02-09 at 2 39 31 pm" src="https://cloud.githubusercontent.com/assets/2281667/22838829/b1b86c76-ef7b-11e6-8049-b9d49a849669.png">

##### Before
<img width="800" alt="screen shot 2017-02-09 at 1 03 51 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803159/a72b6e10-eec8-11e6-826e-97a3ae020946.png">

##### After
<img width="1424" alt="screen shot 2017-02-09 at 2 39 36 pm" src="https://cloud.githubusercontent.com/assets/2281667/22838831/b69906a6-ef7b-11e6-911e-7c0fc79866b6.png">

##### Before
<img width="800" alt="screen shot 2017-02-09 at 1 03 56 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803168/b0fee0b6-eec8-11e6-8c0d-1f4055678b5f.png">

##### After
<img width="1386" alt="screen shot 2017-02-09 at 2 39 40 pm" src="https://cloud.githubusercontent.com/assets/2281667/22838842/bbdf61b4-ef7b-11e6-9768-095b83d95a82.png">

##### Before
<img width="800" alt="screen shot 2017-02-09 at 1 04 13 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803177/c0ef2a76-eec8-11e6-8ab9-5f45c4e8477d.png">

##### After
<img width="800" alt="screen shot 2017-02-09 at 1 12 24 pm" src="https://cloud.githubusercontent.com/assets/2281667/22803361/790f1b0c-eec9-11e6-90b3-078131cdc163.png">

**Comment by barryross** [comment]
Was this resolved when I disabled it from the "New Project Wizard?"?  Do all references need to be identified and removed throughout the system?

**Comment by leobardoramon** [comment]
All references need to be identified and removed from the system.

**Comment by barryross** [comment]
Okay, thanks for clarifying

**Comment by barryross** [comment]
I should have clarified my question...would disabling site-wide solve this or do we need to remove all references (including visible, disabled ones) ?

**Comment by leobardoramon** [comment]
The goal is to remove all ( visible ) references

**Comment by barryross** [comment]
@leobardoramon  I assume this includes more obscure references like in the "Metrics" section, correct? http://localhost/js/metrics/metrics.html?sessionid=188

**Comment by barryross** [comment]
@leobardoramon  Please test on `contractor_barry`.  Believe this is resolved. 

Relevant commit: https://github.com/codetodesign/NYUAMS/commit/35a7daff70812b5b994cf3fa15e9bcc5f08838ae

**Comment by leobardoramon** [comment]
Nice work , @barryross !

I notice Laser service in the following place:

 - Projects > session(s) > Add Session WIZ > Panel 1

**Comment by barryross** [comment]
@leobardoramon Thanks!  Good call, missed that one. 
## Projects > session(s) > Add Session WIZ > Panel 1
### Before
<img width="1023" alt="screen shot 2017-02-10 at 10 26 12 am" src="https://cloud.githubusercontent.com/assets/2281667/22838798/8ded8128-ef7b-11e6-9d0e-368eb8709c81.png">

### After
<img width="656" alt="screen shot 2017-02-10 at 10 27 11 am" src="https://cloud.githubusercontent.com/assets/2281667/22838797/8ded1fb2-ef7b-11e6-99cc-8e523e899723.png">

**Comment by barryross** [comment]
@leobardoramon   Relevant commit for fix:


https://github.com/codetodesign/NYUAMS/commit/00a4215b41e50d6cb8e39f7362b59b6654925601

Please test on `contractor_barry`

**Comment by leobardoramon** [comment]
Looks good.  Thank you
