### ISSUE TITLE
( JIRA #35 ) can't edit netID on the edit client page

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#447]
screenshot: http://note.io/1I8AbVW
Also, could we also check to make sure all editable fields are editable?
thanks,

**Comment by NYU-AMS** [comment]
this should be admin only

**Comment by barryross** [comment]
Is this a correct representation of what needs to be in place? 


| Field        | Editable by client | Editable by admin |
| ------------ | ------------------ | ----------------- |
| First name   | Yes                | Yes               |
| Last Name    | Yes                | Yes               |
| NetID        | No                 | Yes               |
| Department   | Yes                | Yes               |
| Univ. status | Yes                | Yes               |
| Email        | Yes                | Yes               |
| Alt email    | Yes                | Yes               |
| Phone #      | Yes                | Yes               |
| Alt #        | Yes                | Yes               |

**Comment by leobardoramon** [comment]
assuming that you meant "Editable by staff" , not "Editable by client" , then yes, this is correct

**Comment by barryross** [comment]
Okay, will creating a new user for myself in admin->users with "normal" permissions allow me test as staff?

**Comment by barryross** [comment]
Believe I have resolved.  Please test on `contractor_barry`

Relevant commit: https://github.com/codetodesign/NYUAMS/commit/91ae0dbaf923286bbd88190a527331188c66bfa4

Video Demo:  https://www.dropbox.com/s/tcbhxf104xhsmzi/447-editable-fields.mov?dl=0
