### ISSUE TITLE
Test Case:  New Client - Remove validation for "Alt Phone Number"

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#452]
Since the Alternate phone number field is also used for phone extensions, please remove the formatting validation for this field
https://drive.google.com/open?id=0B_9JEK6SVk1bLV9uLUc4YUtjcEE&authuser=0

**Comment by barryross** [comment]
I have commented out the validation required a valid telephone number for the ext/alternate phone field.  Please test on contractor_barry 

<img width="617" alt="screen shot 2016-12-30 at 2 10 08 pm" src="https://cloud.githubusercontent.com/assets/2281667/21573512/04cf3a6e-ce9a-11e6-90b7-c8f7b12dc128.png">
<img width="600" alt="screen shot 2016-12-30 at 2 10 12 pm" src="https://cloud.githubusercontent.com/assets/2281667/21573511/04cf1746-ce9a-11e6-8594-08dc55df379e.png">

**Comment by leobardoramon** [comment]
Looks good

**Comment by leobardoramon** [comment]
when testing #447 , I notice that validation is still happening from the Clients>"edit" panel

See screenshots:

<img width="2070" alt="screen shot 2017-02-01 at 5 21 39 pm" src="https://cloud.githubusercontent.com/assets/2165796/22528877/1eee25a4-e8a3-11e6-86fc-472177d2ca6d.png">

<img width="996" alt="screen shot 2017-02-01 at 4 56 07 pm" src="https://cloud.githubusercontent.com/assets/2165796/22528886/275f2ab2-e8a3-11e6-91f0-5291cc936f94.png">

**Comment by barryross** [comment]
@leobardoramon  roger that...I"ll re-visit

**Comment by barryross** [comment]
hmmm, having trouble replicating as this appears to be resolved on my end...can you please re-pull and try again?  

Video demo: 
https://www.dropbox.com/s/qupcfm98doeg7kf/452-alt-number.mov?dl=0

**Comment by leobardoramon** [comment]
Sorry,

To reproduce:

Login
go to Clients page
select the Edit button for any client
add an extension number to the "Alt. Phone Number " field
select the "Submit" button

**Comment by barryross** [comment]
@leobardoramon  Gotcha, problem resolved :)  

Please test `contractor_barry`

relevant commit: https://github.com/codetodesign/NYUAMS/commit/9b30bda9a08910a450d4677801f2303948a9e153

**Comment by leobardoramon** [comment]
Looks good
