### ISSUE TITLE
Test Case: Projects>consultation(s)>New Session> Time Parameters - formatting

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#456]
Time format should always be two-digit format, example:
Yes:   12:05
No:     12:5
See image
![screen shot 2015-04-16 at 10 10 51 am](https://cloud.githubusercontent.com/assets/2165796/7182728/42f174d4-e421-11e4-8cef-45268327e0aa.png)

**Comment by barryross** [comment]
Please check on contractor_barry, here is the related commit: https://github.com/codetodesign/NYUAMS/commit/dfa76f3cf081fc6797cfe6951fba1205b564f6c3

## Video Demo
https://www.dropbox.com/s/46h673trg4fusyy/%23456.mov?dl=0

**Comment by leobardoramon** [comment]
Looks good.
