### ISSUE TITLE
Test Case: Devices>"Deselect" button

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#459]
Strange bugginess with Part Queue table:
1.  table jumps around when selecting different device
2.  table remains after "Deselect" button is clicked

https://drive.google.com/open?id=0B_9JEK6SVk1bYnNXd2puWGZ6T2s&authuser=0

**Comment by NYU-AMS** [comment]
We should send this to Barry

**Comment by barryross** [comment]
Believe I have resolved this!  Please test on `contractor_barry`  

#### Relevant Commit: 
ad710a2e7f5b5b251c33e03880f6dce8bec29c4c

#### Video demo
https://www.dropbox.com/s/opzeg9u6culk2d4/459-table-bugginess.mov?dl=0

**Comment by leobardoramon** [comment]
Looks good
