### ISSUE TITLE
Test Case: Invoice PDF - Handling Fee line

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#463]
![screen shot 2015-05-10 at 4 57 26 pm](https://cloud.githubusercontent.com/assets/2165796/7556252/25b03544-f737-11e4-90b3-9177a3b3a08b.png)

**Comment by leobardoramon** [comment]
Should this also be "invisible" on receipt when no handling fee is implemented

**Comment by barryross** [comment]
Do we want to remove this all together, or is this a 2-part issue?

Option A)
remove it from invoice completely 

Option B)
1) When there is a value in the system, it should be reflected on the invoice (hence 5k issue above)
2) If no value, do not display on invoice

**Comment by leobardoramon** [comment]
Since the handling fee doesn't get added until the Checkout Wizard , you can remove the line completely from "Invoice"

**Comment by barryross** [comment]
okay, thanks

**Comment by barryross** [comment]
Removed handling fee on invoice, please test on `contractor_barry`

Relevant commit: https://github.com/codetodesign/NYUAMS/commit/4c65cfa0009444981303fb33392a5e6df3efe320

![sample_invoice](https://cloud.githubusercontent.com/assets/2281667/22362635/faddb2c6-e418-11e6-8d18-0edc7e0680a2.jpg)

**Comment by leobardoramon** [comment]
Looks good.
