### ISSUE TITLE
Test Case:  Grant Check PDF - formatting, check numbers ≥100

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#468]
see what happens with check numbers ≥100
![screen shot 2015-05-22 at 1 11 15 pm](https://cloud.githubusercontent.com/assets/2165796/7775883/e3156248-0084-11e5-9aa4-1c62bd5c0f18.png)

**Comment by barryross** [comment]
Can I please have some more info on how the checks are created and what role they play in the system?....who is generating them, and when? Thanks!

I was reviewing the "checkgen" folder and the contained script, but could use some more guidance.  Thanks!

**Comment by gosha1128** [comment]
It's best to Follow the check generating path in the server code.  You'll
notice it invokes a python script...i wonder if it will work mac side :)

**Comment by gosha1128** [comment]
Leo you should probably show Barry how this works in EBS...

**Comment by barryross** [comment]
thanks, George

**Comment by leobardoramon** [comment]
Barry, I can spend some time showing you how Grant Check Generation work.

For this issue, we simply need to find where the check template lives and modify that template so that the check number is shifted over ~  2-3 spaces to the left ( to be safe ).

Does this make sense?

**Comment by barryross** [comment]
Leo, thanks for letting me know you can spend some time going over the check generation.  Yah, I wonder if it will work Mac-side. My guess is I will probably have to do this one on dev server.  

From what I have seen so far, the `checkgen` folder and `db/check.js` seem pretty crucial for the process.  I imagine even though it is a small formatting fix, it will take some time for me to get acquainted with the template and to test. 

I don't think I have any more question on this at this time though.

**Comment by gosha1128** [comment]
Yep..check.js

**Comment by barryross** [comment]
K, thanks for the confirmation.

**Comment by barryross** [comment]
Believe I have resolved!  Please test on `contractor_barry`
Relevant Commit: https://github.com/codetodesign/NYUAMS/commit/da6666ec55275024c60ad4ce3e84364b9e8b3376

Example PDF
[00000_425_120.pdf](https://github.com/codetodesign/NYUAMS/files/744055/00000_425_120.pdf)

**Comment by leobardoramon** [comment]
Looks good.

**Comment by NYU-AMS** [comment]
looks good

**Comment by barryross** [comment]
👍
