### ISSUE TITLE
Test Case: Orders>Checkout (Credit Card) - Auth code is lost

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#473]
https://drive.google.com/open?id=0B_9JEK6SVk1bS2I2TmxrTnNhVkU&authuser=0

**Comment by leobardoramon** [comment]
This should always be required

**Comment by barryross** [comment]
Is this issue just regarding the lost display after the transaction, or does it need to validate the entry as well?

**Comment by leobardoramon** [comment]
Not that I can think of.  I think you got it

**Comment by barryross** [comment]
Okay, great...thanks!

**Comment by barryross** [comment]
Believe I have resolved.  Please test on `contractor_barry`. Relevant commit: 4c65cfa

Video Demo: 
https://www.dropbox.com/s/r4ntgyd2mvhcjj4/473-auth-code.mov?dl=0

**Comment by leobardoramon** [comment]
Looks good.

**Comment by barryross** [comment]
👍
