### ISSUE TITLE
Test Case: Orders>Checkout Formatting/Layout - implement scrolling for split payments

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#499]
![checkout panel3 -split payments](https://cloud.githubusercontent.com/assets/2165796/8167596/549314a6-136d-11e5-8c4e-b3c1759f5340.png)

**Comment by barryross** [comment]
Please test on `contractor_barry`

Relevant commit: https://github.com/codetodesign/NYUAMS/commit/220fc06ac34d0ec020e1bce6c7196404e4479f59

Demo of solution: 
https://www.dropbox.com/s/j8wtku8wid2wjet/499-scrollable-split-payments.mov?dl=0

**Comment by leobardoramon** [comment]
Looks good.
