### ISSUE TITLE
Test Case: Orders>New Order (RP) - Layout/Formatting

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#502]
Single-decimal for dollar amount
![pricing -one decimal](https://cloud.githubusercontent.com/assets/2165796/8169683/1e97b3fa-1379-11e5-91c8-f9c63d3c1bf4.png)

**Comment by barryross** [comment]
Please test on `contractor_barry`

<img width="740" alt="screen shot 2016-12-18 at 10 16 18 pm" src="https://cloud.githubusercontent.com/assets/2281667/21302942/c7665cf8-c56f-11e6-8475-86408210391b.png">
<img width="810" alt="screen shot 2016-12-18 at 10 16 29 pm" src="https://cloud.githubusercontent.com/assets/2281667/21302941/c75fe85a-c56f-11e6-94f4-41a8efff11f0.png">

**Comment by leobardoramon** [comment]
looks good
<img width="691" alt="screen shot 2017-02-28 at 11 59 47 pm" src="https://cloud.githubusercontent.com/assets/2165796/23446494/04d3b0c4-fe12-11e6-9346-5bd42d4acd9c.png">
