### ISSUE TITLE
Test Case: Orders>New Order>panel6 - Layout/Formatting

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#504]
Default Part Name
![orders new panel6 file name](https://cloud.githubusercontent.com/assets/2165796/8169720/5ffbbb0c-1379-11e5-9a6a-3d211929fdd9.png)

**Comment by gosha1128** [comment]
low effort

**Comment by barryross** [comment]
Looks like we should open another issue for the related, but separate "additional  parts window/option?" 
<img width="920" alt="screen shot 2016-12-18 at 3 52 28 pm" src="https://cloud.githubusercontent.com/assets/2281667/21297738/fd634f72-c539-11e6-980f-a76a7b09f644.png">

**Comment by gosha1128** [comment]
Yep... go ahead and submit issues as you see them and assign to Leo. Leo
will triage later and we'll figure out priority and issue them in a follow
up batch.

If it's high priority we might include them in the current batch thus we
would need an estimate sooner than later...

**Comment by barryross** [comment]
Okay, thanks for letting me know.  Sounds good...I spoke with Leo on Friday about getting the  next estimate in when I'm about 40% done with the current one....I think he mentioned by January 1st, but I am expecting to have it in to you guys sooner.  Are we good in that respect?

**Comment by barryross** [comment]
Okay, after this one, I have a much better idea of how the order panel is laid out and works.  Leo, please test on `contractor_barry`

<img width="1000" alt="screen shot 2016-12-18 at 5 23 16 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298554/624b114c-c547-11e6-9036-4d23bc9a0182.png">
<img width="774" alt="screen shot 2016-12-18 at 5 23 38 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298550/62492274-c547-11e6-8535-d857e89fb9f0.png">
<img width="948" alt="screen shot 2016-12-18 at 5 24 49 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298552/624a914a-c547-11e6-9226-5eef4d9b3642.png">
<img width="772" alt="screen shot 2016-12-18 at 5 25 12 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298551/6249f23a-c547-11e6-9ce1-1cd6c4442c13.png">
<img width="1060" alt="screen shot 2016-12-18 at 5 25 27 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298555/624d5b46-c547-11e6-893e-425938135862.png">
<img width="868" alt="screen shot 2016-12-18 at 5 25 50 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298553/624ac34a-c547-11e6-93e9-181e7ac4232f.png">

**Comment by gosha1128** [comment]
Sounds good to me...Leo ?

**Comment by barryross** [comment]
Hey guys, I have updated this solution...one thing I now see is that the solution relies on there being previous orders for the current project...so it would not work for the first order of a new project (see attached).   
I have been searching through the global variables and aware of some of the api calls, but do you guys know if an easy way to get the #id of the next order item?  Or a list of all orders as a JS array? I am assuming we need this solution to work for all orders, including the first for a project?

<img width="774" alt="screen shot 2016-12-18 at 10 03 11 pm" src="https://cloud.githubusercontent.com/assets/2281667/21302725/1c36a47e-c56e-11e6-9e72-e7781f6044dd.png">

**Comment by leobardoramon** [comment]
Barry, I'm so sorry (i) that I'm only now noticing this and (ii) for the extra work that it will have caused you,

Andrew has specifically requested that the "Part Name" default to the "File Name" of the file that is being used...

Can you please let us know (1) if there is a character limit, also (2) what will happen when a file with the exact same name is being uploaded (a) will it appear differently?

If there is currently no way to distinguish duplicate file names:

Andrew, is this something we should add as a separate issue?

**Comment by gosha1128** [comment]
Yes...if the scope of the issue changed at all...you should add a new issue
or allow barry to re-estimate the current one

**Comment by barryross** [comment]
@leobardoramon  No problem, it happens :) 

It looks like a filename with more than about 60 characters starts to throw off the layout of the panels. 

For your second question, about the filenames...is that with regards to the uploading of the files themselves, or are you wondering how they would display in the part list. It seems to me, the client could distinguish because of the partname before the filename, correct?  

part1/filename.jpg
part2/filename.jpg

**Comment by leobardoramon** [comment]
Barry,

How do we feel about this issue?  Are you clear with what needs to be done?

**Comment by barryross** [comment]
@leobardoramon sorry for the delay here...yes I am, thanks!

**Comment by barryross** [comment]
Okay, 3D printer still requires a description be typed.  The other options default to the selected file name.  Please test on `contractor_barry`

Relevant commit: https://github.com/codetodesign/NYUAMS/commit/130b625e178df0b89a00b902c0c1c3ee2e1b4e96

**Comment by leobardoramon** [comment]
Barry , one last thing for this issue :

 - can you please add the text "Optional" to appear in the Description text field when the field is blank?

**Comment by barryross** [comment]
@leobardoramon  Similar question to #660 regarding placeholder vs actual text...can you please clarify/confirm?

**Comment by leobardoramon** [comment]
Okay, Barry, in light of Andrew's request for #660 , please ignore my last request.

ty

**Comment by barryross** [comment]
@leobardoramon okay, thanks Leo!
