### ISSUE TITLE
Test Case: Projects>consultation(s)>New Session> Purchase

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#506]
![projects 03consultation s new purchase 4-hour](https://cloud.githubusercontent.com/assets/2165796/8169792/e66998c6-1379-11e5-9f76-b1aef83273cd.png)

**Comment by gosha1128** [comment]
??

**Comment by leobardoramon** [comment]
( Please refer to attached screenshot )

Apply blue halo ( that appears around "Payment Method" dropdown ) to "purchase" or "buy more" buttons when they have been selected

**Comment by barryross** [comment]
The blue halo is the browser's default styling for a "focused" input element.  I thought it may be more effective to have a unique background to indicate which part of wizard they user is on  - "one of the 2 payment options, or if the time selection window is active)...what do you think about using this yellowish background color? 

Video 

https://www.dropbox.com/s/0dos5ztes7frnc7/506-time-formatting.mov?dl=0

<img width="390" alt="screen shot 2016-12-31 at 1 00 29 pm" src="https://cloud.githubusercontent.com/assets/2281667/21579236/028be576-cf59-11e6-9385-f5955d926b15.png">

**Comment by leobardoramon** [comment]
Looks good.
