### ISSUE TITLE
Test Case: Orders>part(s)>Update Part Status - start at "Testing"

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#511]
Can we remove the "Part Created" status and have parts start at "Testing"?
![screen shot 2015-06-16 at 4 55 26 pm](https://cloud.githubusercontent.com/assets/2165796/8194352/1e618a52-1449-11e5-80f7-9a36de020057.png)

**Comment by leobardoramon** [comment]
Wide Format:  Start at "Testing"

RP & 3D: Start at "Awaiting Client Approval"

**Comment by gosha1128** [comment]
ok you are sure ?  low effort

**Comment by leobardoramon** [comment]
Yes, verified by Andrew
