### ISSUE TITLE
Test Case: Projects>consultation(s)>New Session - Back button loses file

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#515]
File disappears from Wizard when "Back" button is selected

File is still downloadable in Projects>file(s) table

https://drive.google.com/open?id=0B_9JEK6SVk1ba3BMcFlRZzJWcEk&authuser=0

**Comment by leobardoramon** [comment]
* it doesn't disappear, it is just no longer visible/selectable in the panel ( file still exists in Projects>file(s) )

**Comment by barryross** [comment]
Please check on `contractor_barry`
Relevant commit:
https://github.com/codetodesign/NYUAMS/commit/eaa507eeb757a0e1afcdc36dd8e52d62b9bce8a1

Video demo:
https://www.dropbox.com/s/7enr1p518br8lcj/515-backbutton-session-wizard.mov?dl=0

**Comment by leobardoramon** [comment]
Looks good.
