### ISSUE TITLE
Test Case:  Orders>Checkout Wiz ( Credit Card ) - "Authorize" button

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#521]
Change wording to something like "Save" or "Confirm" so that the EBS action isn't quite misleading.
![screen shot 2015-07-20 at 4 24 18 pm](https://cloud.githubusercontent.com/assets/2165796/8786494/6ad1f2f0-2efc-11e5-9f82-2695af784a00.png)

**Comment by gosha1128** [comment]
low effort

**Comment by barryross** [comment]
Wording updated, please check on contractor_barry

<img width="646" alt="screen shot 2016-12-16 at 1 34 55 pm" src="https://cloud.githubusercontent.com/assets/2281667/21279329/88191298-c394-11e6-8be9-d97c019b3f43.png">

**Comment by leobardoramon** [comment]
Looks good.
