### ISSUE TITLE
Test Case:  Orders>New Order Wiz ( WF / RP )>panel3 File Upload - add notification

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#533]
When uploading a new file for a New Order, the panel should be locked until file upload is absolutely complete (including thumbnail).  Particularly when files already exist in the project. Maybe with a popup, with wording like "file must be completely uploaded and with a thumbnail in order to proceed"
![screen shot 2015-07-20 at 4 40 21 pm](https://cloud.githubusercontent.com/assets/2165796/8786793/4a086d04-2efe-11e5-8d15-ea827ecb2eb8.png)

**Comment by leobardoramon** [comment]
The AMS can work around this issue for now, but it will be a problem in the future.

**Comment by barryross** [comment]
Does the panel need to "lock" when files are being uploaded for existing orders as well?

**Comment by leobardoramon** [comment]
The panel needs to lock only while a file is uploading ; it will unlock
when file upload is complete and file is visible in panel.

**Comment by barryross** [comment]
okay

**Comment by barryross** [comment]
Okay, thanks

**Comment by barryross** [comment]
Please test on `contractor_barry`

Video: https://www.dropbox.com/s/3x5mnfjtkfg12nb/553-disabled-buttons-during-upload.mov?dl=0

Commit: https://github.com/codetodesign/NYUAMS/commit/447a34617f6efac9aaddc15bd736f8ac8a178091

**Comment by leobardoramon** [comment]
Looks good.
