### ISSUE TITLE
Test Case: Projects>consultation(s)>New Session Wiz>panel3, Time Parameters

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#534]
Wizard gets stuck when (1) Selection (a) "Purchase" for 4-Hour Package or (b) "Buy More" for Additional Time and then (2) going back to Doctor's Hours to use that time.

Server: Production
URL: lgsdb.nyu.edu
user: admin
pass: password
File server mounted: nfs://52.6.228.88/amsfiles

Area: Projects > consultation(s) > New Session Wizard > Panel 3, Time Parameters

Video link:
https://drive.google.com/open?id=0B_9JEK6SVk1bbnh1NllhenhQQ1U

![screen shot 2015-07-20 at 4 53 18 pm](https://cloud.githubusercontent.com/assets/2165796/8787103/1535fcca-2f00-11e5-8d48-7e084f4ac0a0.png)

**Comment by barryross** [comment]
Believe I have resolved this by setting `sest_buyinprogress = false` after radio button clicked.  Please check on `contractor_barry`

Video Demo:
https://www.dropbox.com/s/kpkousgpm9phbo4/534-session-wizard-back.mov?dl=0

Relevant Commit: 
https://github.com/codetodesign/NYUAMS/commit/9f2fdfc6deda2d0d14ef20eb676ea33a53e7017b

**Comment by leobardoramon** [comment]
Looks good.
