### ISSUE TITLE
Test Case:  Projects>consultation(s)>New Session Wiz>panel3, Time Parameters

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#536]
Add text to indicate the the time format is 24-hour / military time.

**Comment by gosha1128** [comment]
low effort

**Comment by barryross** [comment]
Please check on `contractor_barry`

Here is the related commit: https://github.com/codetodesign/NYUAMS/commit/70f080dbc813cd789a5c6bfd2daa13ddb4a63f36


<img width="650" alt="screen shot 2016-12-30 at 7 46 22 pm" src="https://cloud.githubusercontent.com/assets/2281667/21575681/e3f4ee80-cec9-11e6-816c-fcedf37c4b37.png">

**Comment by leobardoramon** [comment]
Looks good
