### ISSUE TITLE
Test Case:  Projects>consultation(s)>New Session>panel3, Time Parameters 

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#537]
Insert a popup or text somewhere so that it is clear to the user that the 4-hour package and additional time must first be purchased before they can be selected

**Comment by gosha1128** [comment]
low effort, user interface ?

**Comment by barryross** [comment]
This is now available for testing on `contractor_barry`

**Comment by leobardoramon** [comment]
Looks good.

**Comment by barryross** [comment]
great, glad to hear!
