### ISSUE TITLE
WIREFRAMES - Admin>account - Main table

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#585]
Please see designs for new Admin>account table:
https://drive.google.com/open?id=0B_9JEK6SVk1beDdEYkdNWG5yaXM

Please begin development

[GAA_main1.pdf](https://github.com/gosha1128/NYUAMS/files/362476/GAA_main1.pdf)

**Comment by gosha1128** [comment]
OK, ready for the first review on DEV.  In order to complete this I'll need to finalize the DB changes.  But you should take a peak now...

**Comment by leobardoramon** [comment]
Yes, it looks good :)

We might need to adjust the width of the columns.

**Comment by gosha1128** [comment]
OK, you can test this now on DEV.  Right now, it will only work when you add a New Account and New Administrator...

**Comment by gosha1128** [comment]
This should be feature complete now, except for "send email".  Please test on DEV...

**Comment by leobardoramon** [comment]
See new design layout:

[Admin_accounts_main5.pdf](https://github.com/gosha1128/NYUAMS/files/433783/Admin_accounts_main5.pdf)

**Comment by gosha1128** [comment]
this may be a duplicate question with another github issue...

what's to be displayed in "email cc" column when they have set some contacts ?  how do they edit once set ?

**Comment by leobardoramon** [comment]
<img width="1431" alt="screen shot 2016-08-26 at 10 41 34 pm" src="https://cloud.githubusercontent.com/assets/2165796/18024743/c728486c-6bdf-11e6-9872-80bbf7d5fe10.png">


Please change button text from "email" to "edit" for table column "email cc"

**Comment by gosha1128** [comment]
Fixed on DEV. please test.

**Comment by leobardoramon** [comment]
Looks good.  Verifired
