### ISSUE TITLE
WIREFRAMES - Admin>accounts - New Account Wiz

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#586]
Please see designs for Admin>accounts> New Account Wiz:
https://drive.google.com/open?id=0B_9JEK6SVk1bMjV4ODR1Mmhmamc
Download:
[GAA_wiz_newaccount1.pdf](https://github.com/gosha1128/NYUAMS/files/362480/GAA_wiz_newaccount1.pdf)

Please begin Development

**Comment by gosha1128** [comment]
ok, you can start testing this on DEV

**Comment by leobardoramon** [comment]
verified

**Comment by leobardoramon** [comment]
Looks good!

**Comment by gosha1128** [comment]
OK, it should be feature complete.  Please do a full test on DEV...

**Comment by leobardoramon** [comment]
Looks good.  Verified

**Comment by leobardoramon** [comment]
<img width="783" alt="screen shot 2016-08-29 at 5 39 01 pm" src="https://cloud.githubusercontent.com/assets/2165796/18068524/b5e94f4c-6e0f-11e6-8696-78db96f41b90.png">
<img width="781" alt="screen shot 2016-08-29 at 5 39 52 pm" src="https://cloud.githubusercontent.com/assets/2165796/18068525/b5e9e72c-6e0f-11e6-82b0-380d7bf2a0d7.png">
<img width="820" alt="screen shot 2016-08-29 at 5 39 59 pm" src="https://cloud.githubusercontent.com/assets/2165796/18068526/b5ed3fee-6e0f-11e6-8e99-a40968067bca.png">
<img width="808" alt="screen shot 2016-08-29 at 5 40 05 pm" src="https://cloud.githubusercontent.com/assets/2165796/18068523/b5e7a67e-6e0f-11e6-9601-e1414422cada.png">

I got an error message when trying to create a new grant account.  I got stuck on the final panel, Grant Administrator Parameters

see video of separate incident:  https://drive.google.com/open?id=0B_9JEK6SVk1banEwTVhOWGtrMW8

**Comment by leobardoramon** [comment]
<img width="833" alt="screen shot 2016-08-29 at 6 12 22 pm" src="https://cloud.githubusercontent.com/assets/2165796/18069310/5e8b8698-6e14-11e6-9d76-9ec5efda6a6f.png">
<img width="1658" alt="screen shot 2016-08-29 at 6 12 45 pm" src="https://cloud.githubusercontent.com/assets/2165796/18069311/5e8d92da-6e14-11e6-9268-8d573477a73c.png">

New account Wiz does not carry over new changes made to email address

**Comment by gosha1128** [comment]
Do you want to allow updating the email address in this UI ?  If so...then
indeed its a bug.  Or I can do the easy thing and allow you not to edit any
of the fields ?

**Comment by leobardoramon** [comment]
would there be an alternate way to update this? via "Clients" tab?

**Comment by gosha1128** [comment]
yes, you can already update client information in clients.  i would rather
keep it there...

**Comment by leobardoramon** [comment]
Okay, this is good for now.  Thank you
