### ISSUE TITLE
WIREFRAMES - Admin>accounts - Edit Account Wiz

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#587]
Please see designs for Admin>account>Edit Account Wiz:
https://drive.google.com/open?id=0B_9JEK6SVk1bWEF0NjRHdjJnYk0

Download:
[GAA_wiz_editaccount1.pdf](https://github.com/gosha1128/NYUAMS/files/362489/GAA_wiz_editaccount1.pdf)

Please begin Development

**Comment by gosha1128** [comment]
OK, first testable version is available for DEV.  Please check it out.  I need to make database changes in order to complete...

**Comment by gosha1128** [comment]
Also, a possible issue.  What if a client is already in our database and you want to associated it with an account.  Currently as designed, the LDAP client you search for will be added as a client, possibly again - or possibly an error if that client netid is already in our system.   Does that make sense ?

**Comment by gosha1128** [comment]
I guess what I am asking...is there an expectation that the account administrator be also a "client" in EBS ?  It seems so...since you basically want me to reuse the client interface.  If thats the case, thats ok - I think it makes it cleaner.  But, it also means you might some slight adjustment to the "client" portion of EBS to accomodate the "administrator" type.  Does that make sense ?

**Comment by leobardoramon** [comment]
This does make sense.

For the time being, let's use the same Client tool to add Grant Administrators.  During the duration of their role as the Grant Administrator, that will be there University Status in the EBS.

Whenever they are replaced in Admin/accounts, their University Status can either (a) revert to the previous status or (b) change to "Other".

**Comment by leobardoramon** [comment]
This looks good so far.  Please proceed with the final integrations

**Comment by gosha1128** [comment]
OK, its now integrated with the database.   It should be feature complete.  Please test on DEV...

**Comment by leobardoramon** [comment]
Looks good. Verified
