### ISSUE TITLE
Test Case:  Orders_Invoice PDF

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#589]
Change "AMS" to "LGS" ( 2nd line from bottom )

[invoice_2016__7__3__18__5_39__399.pdf](https://github.com/gosha1128/NYUAMS/files/427554/invoice_2016__7__3__18__5_39__399.pdf)

**Comment by gosha1128** [comment]
Yep...

**Comment by leobardoramon** [comment]
Please change heading color of "LaGuardia Studio" to de6217

**Comment by barryross** [comment]
I have changed the font and the wording as noted above 

[receipt_2016__11__3__7__31_26__566.pdf](https://github.com/codetodesign/NYUAMS/files/675198/receipt_2016__11__3__7__31_26__566.pdf)

**Comment by leobardoramon** [comment]
Looks good
