### ISSUE TITLE
Test Case:  Orders_Receipt PDF

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#590]
Change "AMS" to "LGS" ( 2nd line from bottom )

[receipt_2016__7__3__16__43_50__813.pdf](https://github.com/gosha1128/NYUAMS/files/427556/receipt_2016__7__3__16__43_50__813.pdf)

**Comment by gosha1128** [comment]
Ah ok

**Comment by leobardoramon** [comment]
Please change heading color of "LaGuardia Studio" to de6217

**Comment by barryross** [comment]
I have changed the font and the wording as noted above.  Please test on contractor_barry
[receipt_2016__11__3__7__31_26__566.pdf](https://github.com/codetodesign/NYUAMS/files/675201/receipt_2016__11__3__7__31_26__566.pdf)

**Comment by leobardoramon** [comment]
Looks good.

**Comment by barryross** [comment]
@leobardoramon 👍
