### ISSUE TITLE
WIREFRAMES - Admin>account - Email Popup, ALL

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#591]
See wireframes

[Admin_accounts_panel_email_all.pdf](https://github.com/gosha1128/NYUAMS/files/428166/Admin_accounts_panel_email_all.pdf)

**_AWAITING APPROVAL**_

**Comment by leobardoramon** [comment]
See -APPROVED- wireframes

[Admin_accounts_emailall2.pdf](https://github.com/gosha1128/NYUAMS/files/433779/Admin_accounts_emailall2.pdf)

**Comment by gosha1128** [comment]
OK, done.  Pls test on DEV...make sure to change the email destinations to your email for all admins and cc's and report users...

**Comment by leobardoramon** [comment]
email does not send ; 
email does not appear in Admin/emails table

**Comment by leobardoramon** [comment]
I'm testing this feature again...so far I've waited 20 minutes and only 6 out of 17 emails have been delivered.

**Comment by gosha1128** [comment]
Can you test it again and make sure all the emails appear in the admin/email table ?  ( sent or not ? )

**Comment by leobardoramon** [comment]
All emails appear in the Admin/email table ( including email cc addresses ).

None of the emails were sent

Email Set 1

<img width="1671" alt="screen shot 2016-08-30 at 1 18 18 pm" src="https://cloud.githubusercontent.com/assets/2165796/18099522/eb962d90-6eb4-11e6-8ca6-9801a1a59b79.png">

Email Set 2 ( with Email ccs )

<img width="1664" alt="screen shot 2016-08-30 at 1 22 42 pm" src="https://cloud.githubusercontent.com/assets/2165796/18099523/eb973f78-6eb4-11e6-8ea2-9bb3d23b4210.png">

**Comment by gosha1128** [comment]
Great.  Looks like there was an error for each one ( error = True ).  I'll
focus around that...

**Comment by gosha1128** [comment]
Here is the error from the SMTP server:

Error: Invalid greeting from server - 421 4.3.2 Connection rate limit
exceeded.

Can you check with AMS or ITS about how to get this limit increased ?

On Tue, Aug 30, 2016 at 10:25 AM, George Williams <george.williams@gmail.com

**Comment by leobardoramon** [comment]
Andrew believes that this is a "Bulk Email" issue from NYU's end.  Their policies are too strict for us to get an increase.  Is there a way that we can send these emails in smaller bunches?

I'm not sure what the email limit is, let's try bunches of 5 accounts ( this way if each one has 1-2 email cc addresses, they should still be fine ).

**Comment by gosha1128** [comment]
OK, added some code to hopefully work around the bulk email issues we've been having.  Please test all the email functionality...

**Comment by leobardoramon** [comment]
Everything looks good.  Please proceed

**Comment by leobardoramon** [comment]
Is there anything left to do?

**Comment by gosha1128** [comment]
I think the new admin/account features are done.    This fix should also
take care of any open admin email bugs...maybe search/close those...

-g
