### ISSUE TITLE
WIREFRAMES - Admin>account - Email Popup, INDIVIDUAL

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#592]
See wireframes

[Admin_accounts_panel_email_individual.pdf](https://github.com/gosha1128/NYUAMS/files/428168/Admin_accounts_panel_email_individual.pdf)

**_AWAITING APPROVAL**_

**Comment by leobardoramon** [comment]
See -APPROVED- wireframes:

[Admin_accounts_email2.pdf](https://github.com/gosha1128/NYUAMS/files/433782/Admin_accounts_email2.pdf)

**Comment by gosha1128** [comment]
OK, please check out what i have so far on DEV.  I made a small adjustment so tell me its ok.  I let you edit the subject area to add your comments, instead of a separate comments area.

**Comment by leobardoramon** [comment]
Right now, the system doesn't detect which "email" button on the table is being selected, the row must first be selected.  If a row is already selected, the "Email To" field defaults to that other row.

See video:  https://drive.google.com/open?id=0B_9JEK6SVk1bN1BWb2lFMUFDTHc

**Comment by leobardoramon** [comment]
can we have the system detect which row the email button exists in?

**Comment by gosha1128** [comment]
OK the selection thing is fixed.  Try again on DEV...

**Comment by leobardoramon** [comment]
looks good.  Verified

**Comment by leobardoramon** [comment]
Followup testing required to test that email sends

**Comment by gosha1128** [comment]
yes...note that the email will work for real so its best to send to
yourself via your ldap identity.

**Comment by leobardoramon** [comment]
Yes, looks good so far.  Please proceed

**Comment by gosha1128** [comment]
Done...please test on DEV.

**Comment by leobardoramon** [comment]
See Screenshot:
<img width="2272" alt="screen shot 2016-09-06 at 3 54 10 am" src="https://cloud.githubusercontent.com/assets/2165796/18266122/1345b306-73e7-11e6-84d0-62f4da1346d9.png">

Error caused server to stop ; Email not sent.

See video ( 25.1 seconds ) : https://drive.google.com/open?id=0B_9JEK6SVk1bbUNDNUdWQWFobEE

**Comment by gosha1128** [comment]
Was there any CC associated with this email or was it empty ?  Can you check ?

**Comment by leobardoramon** [comment]
There was no CC associated.  I got the error for the two bottom accounts for sure ( Labs ; College of Nursing, Nursing Labs ).

**Comment by gosha1128** [comment]
OK, i added some defensive code to check for null.  Please test on DEV
again.

**Comment by leobardoramon** [comment]
Okay, it seems to work fine...Terminal is doing this now:

<img width="592" alt="screen shot 2016-09-06 at 1 44 57 pm" src="https://cloud.githubusercontent.com/assets/2165796/18284505/3bd6e2f8-7438-11e6-8336-d1022c10f320.png">

I assume you're already aware of that.

**Comment by gosha1128** [comment]
Yes, its in a VERBOSE logging mode.  I usually switch it off...but its
useful I think while we are debugging email stuff.

**Comment by gosha1128** [comment]
is this assigned back to me...because you want me to turn the debugging
verbose off ?  Or is there still an issue with my fix for the crash ?

**Comment by gosha1128** [comment]
If its the former...i turned off the verbose logging.

**Comment by leobardoramon** [comment]
Sorry about that. It's updated. Thank you
