### ISSUE TITLE
WIREFRAMES - Admin>account - Email PDF Layout

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#593]
See wireframes

[GAA_email_pdf_layout.pdf](https://github.com/gosha1128/NYUAMS/files/428170/GAA_email_pdf_layout.pdf)

**_AWAITING APPROVAL**_

**Comment by leobardoramon** [comment]
-APPROVED-

See wireframes (above)

**Comment by leobardoramon** [comment]
Please change heading color of "LaGuardia Studio" to de6217

**Comment by leobardoramon** [comment]
<img width="824" alt="screen shot 2016-08-26 at 10 40 21 pm" src="https://cloud.githubusercontent.com/assets/2165796/18024729/5a1a790c-6bdf-11e6-86fa-9ab0099a9533.png">

Please:

 - add "$"s where needed

 - Change figures to reflect "Remaining Balance", not "amount used"

**Comment by gosha1128** [comment]
Fixed - test on DEV.

**Comment by leobardoramon** [comment]
Looks good.  Verified.

**Comment by leobardoramon** [comment]
See details within screenshots:

<img width="1685" alt="screen shot 2016-09-06 at 4 25 09 am" src="https://cloud.githubusercontent.com/assets/2165796/18266913/cfe01bc0-73ea-11e6-97db-7021f228cb40.png">
<img width="826" alt="screen shot 2016-09-06 at 4 25 24 am" src="https://cloud.githubusercontent.com/assets/2165796/18266912/cfded148-73ea-11e6-8b5a-6a698a898ab9.png">

Please adjust (1) Client Name and (2) Client Net ID info in Grant Check table.  Thank you.

**Comment by gosha1128** [comment]
Should be fixed now on DEV.  pls test.

**Comment by leobardoramon** [comment]
See screenshot notes:

<img width="840" alt="screen shot 2016-09-06 at 1 50 14 pm" src="https://cloud.githubusercontent.com/assets/2165796/18284729/108db152-7439-11e6-8882-ca5cff4740d8.png">

**Comment by leobardoramon** [comment]
Can the "netid" field be associated with the "Client" Net ID ?

It is currently using the "user" login

**Comment by gosha1128** [comment]
Isn't it the admin who checked them out ?

**Comment by leobardoramon** [comment]
The net id field is intended for the net id of the client

**Comment by gosha1128** [comment]
ok thanks for the clarification !

**Comment by gosha1128** [comment]
ok fixed on dev, pls test.

**Comment by leobardoramon** [comment]
Looks good.
