### ISSUE TITLE
WIREFRAMES - Admin/account - Grant Administrator

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#597]
The Grant Administrator is considered a "Client" in the system, with the University Status of "Grant Administrator.

We will have this portion of the New Account Wizard work the same way as New Client.  If the Grant Administrator aka client is already in the system, the user will "skip LDAP search" and pull their name up directly from the EBS.

Once an existing client is assigned to a Grant Account, there will be a popup warning:

```
   "The client already exists in the system.  University Status is being set to Grant Administrator"
```

**Comment by gosha1128** [comment]
This should work now.  Please test on dev when you can.

**Comment by leobardoramon** [comment]
I'm not sure how this is supposed to work.  I added a client from the "Client" tab, and then pulled up that same client from the Admin/accounts/"New Account Wizard",

The bad news:  there was no popup warning ( not sure how bad that news is )

The good news: it modified the existing client ( did not create a duplicate )

see video of my test here:  https://drive.google.com/open?id=0B_9JEK6SVk1baE5rcVNHVEpvRDg

**Comment by gosha1128** [comment]
yep...looks like i'm missing the warning alert...please assign back to me

**Comment by gosha1128** [comment]
OK, its fixed on DEV.  please test when you get a chance.

**Comment by leobardoramon** [comment]
Looks good.

Final request:  Can we have contact information carried over to the New Account Wizard?

Should we add this as a separate enhancement for later?

**Comment by gosha1128** [comment]
Yes anything can be done !

My preference is that you submit a separate github issue and review with
AMS if its important for this release and assign it accordingly.

I'm trying to focus all time and effort to get this release out :)
