### ISSUE TITLE
Test Case:  Admin/account/"New Account Wizard" - Existing Grant Account Admin contact info

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#600]
For Grant Administrators that already exist in the Client database, currently their contact information is not carried over to Grant Account Table in Admin/accounts.

Can we have their existing contact information carried over into the New Account Wizard?

**Comment by gosha1128** [comment]
Ah yes...I see...I should fix it now.  I wonder if an alert should appear
saying something like...we found this user in our system, carrying over
settings...

**Comment by leobardoramon** [comment]
I would recommend using the existing popup alert that you just created, and introducing it in one panel earlier.

**Comment by gosha1128** [comment]
OK, I already ran with something...i put an alert after LDAP search.

Please let me know if this works for now...you can test now.

**Comment by leobardoramon** [comment]
Yes, looks good. Verified.
