### ISSUE TITLE
Test Case:  Queue Tab - Device Identification

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#601]
There is no way of knowing which device is selected in the Queue tab

See screenshot below

<img width="1388" alt="screen shot 2016-08-23 at 3 37 38 pm" src="https://cloud.githubusercontent.com/assets/2165796/17912186/19486898-6960-11e6-8bd0-550382f1b126.png">

**Comment by gosha1128** [comment]
Ah yes.  OK...can i have the server now?  This kind of live dev and testing
may work better if you are in the codetodesign slack room right now :)

**Comment by gosha1128** [comment]
OK, i did a quick fix.  Its not your UI exactly...but hopefully is workable
rightnow...

**Comment by leobardoramon** [comment]
Yes, it's good for now.  Thank you
