### ISSUE TITLE
WIREFRAMES - Admin>account - Main table, "email cc" "edit" button

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#602]
See wireframes:

[Admin_accounts_editemailcc.pdf](https://github.com/gosha1128/NYUAMS/files/433784/Admin_accounts_editemailcc.pdf)

**Comment by gosha1128** [comment]
OK, i see the email cc button in your design.  Questions-

1) what happens when they actually set some contacts, should the column now show those emails ?  what if they want to edit ?

2) how do they separate the emails in the text box ( a comma ) ?

3)  should be validate the email addresses and alert with an error ?

**Comment by leobardoramon** [comment]
1)  The column doesn't need to show the email addresses, only the "edit" button

2)  I've updated the design with a note below the text field "separate email addresses with commas (,) or semicolons (;).  ( see below ) So let's do it that way

3) Does email address validation require the email address to receive an actual email?  If so, then no email validation.  I'm concerned that email addresses will receive multiple validation emails every time a user "edits" this list

[Admin_accounts_editemailcc2.pdf](https://github.com/gosha1128/NYUAMS/files/435702/Admin_accounts_editemailcc2.pdf)

<img width="435" alt="screen shot 2016-08-24 at 5 20 56 pm" src="https://cloud.githubusercontent.com/assets/2165796/17948608/88814648-6a1f-11e6-9670-34251cd4aa46.png">

**Comment by gosha1128** [comment]
OK, i'm only supported comma separation at the moment.  Hope thats ok.

**Comment by leobardoramon** [comment]
<img width="507" alt="screen shot 2016-08-29 at 6 16 10 pm" src="https://cloud.githubusercontent.com/assets/2165796/18069464/3f01d484-6e15-11e6-9ea2-b057e502841f.png">

This email was never received

**Comment by gosha1128** [comment]
fixed on dev - pls test.

**Comment by leobardoramon** [comment]
Yes, it works.  Verified.
