### ISSUE TITLE
Test Case:  Queue Tab ( List View )/Part Status Update - Remove two statuses from UI

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#623]
Please remove "Part Created" and "Test Complete" from the list of part statuses.

Screenshot:

**Comment by leobardoramon** [comment]
screenshot:
<img width="572" alt="screen shot 2016-09-21 at 9 23 31 am" src="https://cloud.githubusercontent.com/assets/2165796/18712764/d60a9f26-7fdd-11e6-951e-3c1f545b3762.png">

**Comment by gosha1128** [comment]
Fixed on DEV so you can test.  I'm a bit concerned about how removing this affects any other behavior that depends on these status...so make sure to do  a good test.
