### ISSUE TITLE
Create contractor area

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#645]
We need to create a contractor area of the LGS with all fake data.

What exactly will the area need to encompass?

Will we need an entirely new aws environment?

**This will need to be ready within the next two weeks**

**Comment by leobardoramon** [comment]
George,
Do you think we need a separate VPC ( Virtual Private Cloud ) for DEV_contractor ?

I think that if we implement the Turnkey file sever, we'll be set as far as security.

Andrew, thoughts?

**Comment by gosha1128** [comment]
Yes...we just can't use any actual customer data in this environment...

**Comment by leobardoramon** [comment]
cool

**Comment by leobardoramon** [comment]
- 1 - Contractor area is up and running in AWS:

 - 2 - Our new coder, Berry Ross's Public IP address has been added to the Inbound security group rules for (1) DEVEBS,DEVEBS_contractor (2) DEVFILES,DEVFILES_contractor for ALL TRAFFIC

![screen shot 2016-11-11 at 2 51 31 am](https://cloud.githubusercontent.com/assets/2165796/20208191/6e2af7f2-a7ba-11e6-9126-11c7cc0b8c70.png)
![screen shot 2016-11-11 at 2 51 59 am](https://cloud.githubusercontent.com/assets/2165796/20208192/6e2c5110-a7ba-11e6-939f-09bbaf302b52.png)

 - 3 - Once DEVFILES has been wiped of data, we will begin to populate with scrambled data

**Comment by leobardoramon** [comment]
- 4 - Berry's Public IP has been added to DEVFILES_contractor/etc/exports/

![screen shot 2016-11-11 at 3 03 51 am](https://cloud.githubusercontent.com/assets/2165796/20208368/be6dfc68-a7bb-11e6-9441-56ac65748ed2.png)

**Comment by leobardoramon** [comment]
*unknown keyword "insecture"

![screen shot 2016-11-11 at 3 07 23 am](https://cloud.githubusercontent.com/assets/2165796/20208423/14e3ffd4-a7bc-11e6-9567-7ac334c2a985.png)
