### ISSUE TITLE
Test Case:  QUEUE page/main - Please remove all services except Wide Format from the Queue page

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#646]
Wide Format Archival Printing will be the only service using the Queue page for LGS EBS v2

Please remove the buttons for all other services from this page

- APPROVED -

See Wireframes:

<img width="2089" alt="screen shot 2016-11-03 at 7 34 56 pm" src="https://cloud.githubusercontent.com/assets/2165796/19989661/673baf0c-a1fe-11e6-8bb2-74a455afd6f8.png">

**Comment by barryross** [comment]
fixed, please check on branch contractor_barry  
<img width="455" alt="screen shot 2016-11-23 at 5 10 41 pm" src="https://cloud.githubusercontent.com/assets/2281667/20583532/c29f7b3e-b19f-11e6-9032-cd2b802c601d.png">

**Comment by leobardoramon** [comment]
fixed on DEV.  See followup issue, #656
