### ISSUE TITLE
Test Case:  QUEUE page/main table - "Download"/Locate works properly

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#647]
We need the "Locate" button in the "Download" popup to work properly

- APPROVED -

See wireframe:
<img width="2088" alt="screen shot 2016-11-03 at 7 37 27 pm" src="https://cloud.githubusercontent.com/assets/2165796/19989709/d440cd08-a1fe-11e6-9cd6-acef6970aed9.png">

**Comment by barryross** [comment]
Fixed, please test on contractor_barry branch

**Comment by leobardoramon** [comment]
fixed on dev
