### ISSUE TITLE
Test Case:  QUEUE page/main table - Remove "Completed" parts from Queue Table

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#648]
Once a part has reached the status "Part Completed", it should be removed from the queue

- APPROVED - 

See wireframe:
<img width="2088" alt="screen shot 2016-11-03 at 7 36 44 pm copy" src="https://cloud.githubusercontent.com/assets/2165796/19989768/345d7060-a1ff-11e6-87ee-29fba9e36db0.png">

**Comment by barryross** [comment]
appears to be resolved already

**Comment by leobardoramon** [comment]
fixed on dev
