### ISSUE TITLE
Test Case:  Orders/New Order Wizard - Disable Device "Sweet Zombie"

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#650]
Please disable this device in the "Device" dropdown for Wide Format Printing Service in the New Order Wizard

**Comment by barryross** [comment]
Believe this is now resolved, please test on contractor_barry branch
<img width="626" alt="screen shot 2016-11-23 at 4 09 34 pm" src="https://cloud.githubusercontent.com/assets/2281667/20582693/47264bf6-b198-11e6-9cb2-bd65d236a0d5.png">

**Comment by leobardoramon** [comment]
fixed on dev
