### ISSUE TITLE
Test Case:  Orders/part(s)/Add Part Wiz - disable Device "Sweet Zombie"

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#651]
Please disable this device in the "Device" dropdown for Wide Format Printing Service in the Add Part Wizard

**Comment by barryross** [comment]
Is this referring to the part calculator?  I'm unsure which "new part wizard" you are referring to. 
<img width="618" alt="screen shot 2016-11-23 at 4 10 33 pm" src="https://cloud.githubusercontent.com/assets/2281667/20582621/8f14a2e2-b197-11e6-9254-bd1784b33c25.png">

**Comment by leobardoramon** [comment]
fixed on dev
