### ISSUE TITLE
Test Case:  Orders/New Order Wiz - Remove Service "Laser"

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#652]
Please disable this Service in the "Service Type" dropdown in the New Order Wizard

**Comment by barryross** [comment]
Okay, I believe I have disabled it.  I still need to test locally, but have pushed my commit, as I wanted to test write permissions.

**Comment by barryross** [comment]
Okay, confirmed this is disabled on my local machine

**Comment by leobardoramon** [comment]
fixed on dev
