### ISSUE TITLE
Test Case:  Admin>accounts>New Account WIZ - Server Crash

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#654]
IP:  54.157.58.239
pem: contractor_ebs.pem

login: barry
pass: barry
domain: Local

when going through the wizard to completion, the server crashes

![screen shot 2016-11-17 at 6 08 26 pm](https://cloud.githubusercontent.com/assets/2165796/20412191/3327e9d8-acf3-11e6-99f7-80a2e9934c50.png)

![screen shot 2016-11-17 at 5 27 00 pm](https://cloud.githubusercontent.com/assets/2165796/20411523/dd544eaa-acef-11e6-96d7-c5f7df792b57.png)
![screen shot 2016-11-17 at 5 34 14 pm](https://cloud.githubusercontent.com/assets/2165796/20411524/dd565b46-acef-11e6-860a-c96beda12a25.png)

**Comment by barryross** [comment]
Believe I have fixed this...please test on contractor_barry branch.  Thanks!

**Comment by leobardoramon** [comment]
fixed on dev
