### ISSUE TITLE
Test Case:  QUEUE page/main - Please remove Device "Sweet Zombie" from Wide Format service from the Queue page

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#656]
see image below:

![screen shot 2016-12-07 at 1 37 59 am](https://cloud.githubusercontent.com/assets/2165796/20957610/ec496470-bc1e-11e6-9edf-5c6c059a1241.png)

**Comment by barryross** [comment]
I have removed "Sweet Zombie" from the queue page when selecting Wide Format.  Please test on contractor_barry

**Comment by barryross** [comment]
<img width="1088" alt="screen shot 2016-12-09 at 10 43 42 am" src="https://cloud.githubusercontent.com/assets/2281667/21060425/2eeaf71a-bdfc-11e6-9368-5703e2bb83da.png">

**Comment by leobardoramon** [comment]
Looks good.
