### ISSUE TITLE
We need a way to sort Projects and order alphabetically 

### ISSUE THREAD

**Issue by NYU-AMS** [codetodesign/NYUAMS#658]
We need a way to sort Projects and order alphabetically in both active and closed states.

![orders](https://cloud.githubusercontent.com/assets/5067173/21054408/9af36a92-bdfb-11e6-8711-6eda030b0b68.jpg)
![projects](https://cloud.githubusercontent.com/assets/5067173/21054409/9af8a4da-bdfb-11e6-86a6-c4937f9f8220.jpg)

**Comment by NYU-AMS** [comment]
can we add this to Barrys plate?

**Comment by leobardoramon** [comment]
Currently, Projects can be sorted alphabetically through the Projects page, but if we can make the "Project [Name]" column in the Orders page sortable, that would be great ( see image below )

Andrew, does this work for the LGS?

<img width="2097" alt="screen shot 2016-12-09 at 12 55 44 pm" src="https://cloud.githubusercontent.com/assets/2165796/21059215/5bd4856c-be0f-11e6-8d3d-90413e537d98.png">

**Comment by NYU-AMS** [comment]
yes that would be helpful.

**Comment by barryross** [comment]
@leobardoramon @gosha1128 Okay, after diving pretty deep into this one, in the api and db files, the best model I had to work off of was the search mechanism.  I leveraged some of the same custom sql queries, and the mechanisms by which the api talks to the db.  

You'll see the pagination is off in a similar fashion to the "search" mechanism...that being said, does this solution work for this issue?  

https://www.dropbox.com/s/m1380yxdusp64q0/658-project-name-sorting.mov?dl=0

**Comment by gosha1128** [comment]
What did you need me to do ?

**Comment by leobardoramon** [comment]
Can you please answer Barry's db question <above>?

**Comment by gosha1128** [comment]
Looks good to me.  I say if it passes testing then go with it...

**Comment by barryross** [comment]
👍  thanks guys

**Comment by leobardoramon** [comment]
Looks good.
