### ISSUE TITLE
Orders>Part Add/Update

### ISSUE THREAD

**Issue by barryross** [codetodesign/NYUAMS#660]
Similar issue to <a href="https://github.com/codetodesign/NYUAMS/issues/504">#504</a>, but for adding new parts

<img width="1139" alt="screen shot 2016-12-18 at 5 33 51 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298617/446c688c-c548-11e6-8bfc-bb8ff89badb4.png">

<img width="403" alt="screen shot 2016-12-18 at 5 35 31 pm" src="https://cloud.githubusercontent.com/assets/2281667/21298632/6b9bee32-c548-11e6-81f3-86f5cac45fad.png">

**Comment by barryross** [comment]
Hey Leo, is this an issue we should tackle as well?

**Comment by leobardoramon** [comment]
yes, please.  Thank you for putting this on our radar.

**Comment by barryross** [comment]
Okay,  I assume this would be a separate issue and will add it to "vetting" list for now, and include it on upcoming estimate?  You're welcome for putting it on your radar.

**Comment by gosha1128** [comment]
Yes, keep separate lists if thats cool

--already vetted and working on
--already estimated but need to re-estimate because scope changed
--need to estimate

George

**Comment by barryross** [comment]
Sure thing, will do

**Comment by barryross** [comment]
Turns out resolving #504, actually seemed to make this a non-issue.  Here is some initial testing I've done.  Note, I didn't test all 3 rapid printer options in the video:

https://www.dropbox.com/s/tq9quxhd1kognpx/660-new-part-description.mov?dl=0

**Comment by leobardoramon** [comment]
Barry one more thing, same as #504 :

 - can you please add the text "Optional" to appear in the Description text field when the field is blank?

**Comment by barryross** [comment]
@leobardoramon as a placeholder instead of "enter", or actual text as if the user had typed it in?  Also, it will be overwritten when they select an image...is that what you/client wants?

**Comment by leobardoramon** [comment]
Andrew,

Let us know what you would like.

**Comment by buck0land** [comment]
Yes let have it overwrite when you select the file.  no need to have a user type anything

**Comment by barryross** [comment]
@buck0land thanks Andrew!

**Comment by leobardoramon** [comment]
Looks good.
