### ISSUE TITLE
Terminal, DEVEBS : >node app.js nfs - unable to start server

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#664]
After pulling the latest changes from GitHub ( origin contractor_barry ), I'm getting an error when I run the command line:

 - >node app.js nfs

I've already modified the file ".../db/config.js" to match the DEVEBS connection string.

See image:
![screen shot 2017-01-09 at 2 00 35 pm](https://cloud.githubusercontent.com/assets/2165796/21779199/7f4f9c16-d674-11e6-84a9-4e0d5a9ca673.png)

Can anyone help?

**Comment by leobardoramon** [comment]
I ran the command:

 - >npm install moment-timezone

Seems to work now.  Thanks all <3

**Comment by barryross** [comment]
Hey Leo, just read your comment and that’s what I was going to suggest.  

Actually, npm install moment-timezone —save may be helpful to ensure ints in your package.json
