### ISSUE TITLE
UI: Queue Page - Queue Table, Column 1

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#668]
Please fix the broken images in Column 1 of Queue page

<img width="2359" alt="screen shot 2017-01-17 at 2 29 09 pm" src="https://cloud.githubusercontent.com/assets/2165796/22039809/c01a712a-dcce-11e6-8325-39ec456cbb79.png">

**Comment by barryross** [comment]
@leobardoramon I'm assuming the thumbnail in column one should correspond to the file in "filename" and the one available in "download" ?

**Comment by leobardoramon** [comment]
tbh ( to be honest ) I'm sure what the intended image is supposed to be.

I would prefer either (a) removing the column altogether or (b) leaving the column but removing the "image" that is being called for.  Whichever is easier/quicker to implement.

**Comment by barryross** [comment]
@leobardoramon  okay, probably leaving the column and removing the image would be easiest

**Comment by leobardoramon** [comment]
sounds good

**Comment by barryross** [comment]
Believe this is resolved, please test on `contrator_barry`
Relevant commit: 4c0247962da6175781dedeae19081b753a3f4096

<img width="971" alt="screen shot 2017-01-20 at 10 31 20 am" src="https://cloud.githubusercontent.com/assets/2281667/22160647/58664bec-defb-11e6-9c77-a4ae6396e594.png">
<img width="391" alt="screen shot 2017-01-20 at 10 31 30 am" src="https://cloud.githubusercontent.com/assets/2281667/22160646/5865ca1e-defb-11e6-9ba7-d333e72820b7.png">

**Comment by leobardoramon** [comment]
Looks good
