### ISSUE TITLE
UI : Queue Table - Columns 10 , 11 , 14

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#669]
Please fix the initial appearance of the buttons in Columns 10 , 11 , 14

<img width="2359" alt="screen shot 2017-01-17 at 2 29 09 pm" src="https://cloud.githubusercontent.com/assets/2165796/22040041/887ece04-dccf-11e6-9617-4802fbf7de03.png">

**Comment by barryross** [comment]
I'm actually seeing consistency with them and "download", "replace", but I can style them all to look more like "download" and "replace" do in your screencap. 

<img width="1296" alt="screen shot 2017-01-17 at 4 17 42 pm" src="https://cloud.githubusercontent.com/assets/2281667/22045646/48e64c1c-dcd0-11e6-87c6-a81e9381dad4.png">

**Comment by barryross** [comment]
That sound like a plan?

**Comment by leobardoramon** [comment]
I'm okay with what you decide , as long as they all look consistent from the client's end

**Comment by barryross** [comment]
👍

**Comment by barryross** [comment]
Believe this is resolved. 

Please test `contractor_barry`

Relevant commit: b9d3af3211db3e5093feab96aaf8175f0740bedd
<img width="1380" alt="screen shot 2017-01-20 at 1 25 19 pm" src="https://cloud.githubusercontent.com/assets/2281667/22166009/afef73e4-df13-11e6-82e2-6f7e6fadf53b.png">

**Comment by leobardoramon** [comment]
Looks good.
