### ISSUE TITLE
UI : Orders > part(s) > Change Part Status PANEL - remove empty radio buttons

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#670]
Please remove the empty radio buttons from the UI of this panel

<img width="576" alt="screen shot 2017-01-17 at 2 28 26 pm" src="https://cloud.githubusercontent.com/assets/2165796/22040181/fe4b7a9c-dccf-11e6-821b-4348beb484e1.png">

**Comment by barryross** [comment]
@leobardoramon I'm having trouble finding this popup/wizard in orders -> parts 
Where do I find it? 

<img width="1305" alt="screen shot 2017-01-17 at 4 09 11 pm" src="https://cloud.githubusercontent.com/assets/2281667/22045432/0bfa0a56-dccf-11e6-881a-a91e4cfe0db8.png">

**Comment by barryross** [comment]
I think the fact that I can't see it may have to do with this? 
<img width="365" alt="screen shot 2017-01-17 at 10 44 11 pm" src="https://cloud.githubusercontent.com/assets/2281667/22053975/75303c96-dd08-11e6-9b63-f3a95c9fa194.png">

**Comment by leobardoramon** [comment]
Ah, yes! You have to click on the colored box ( green , yellow , blue , red
) to open the panel

**Comment by barryross** [comment]
ah, thanks!

**Comment by barryross** [comment]
Please test on `contractor_barry`

Relevant Commit: b57000d402e96ca3d21416c438629f1a3d96bb07

<img width="1344" alt="screen shot 2017-01-20 at 4 04 11 pm" src="https://cloud.githubusercontent.com/assets/2281667/22169629/5f66546c-df2a-11e6-9a04-23c634669ca1.png">

**Comment by leobardoramon** [comment]
Looks good.
