### ISSUE TITLE
Test Case : Orders > New Order Wiz - Initial Part Status

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#671]
When a new order is created, the initial status that the part is assigned is "Part Created"

Please change to initial Part Status to "Testing" ( the Part Statuses "Part Created" and "Test Complete" have been removed from the UI workflow )

<img width="1064" alt="screen shot 2017-01-17 at 2 28 43 pm" src="https://cloud.githubusercontent.com/assets/2165796/22040354/8b050980-dcd0-11e6-9194-48bb96e34a9e.png">

**Comment by barryross** [comment]
Pretty sure #672 will resolve this, but I'll be sure to check

**Comment by barryross** [comment]
This should now be resolved.  Please test on `contractor_barry`

Relevant Commit: 2cea593e7196e7086d0810987eb006e429e597bd

**Comment by leobardoramon** [comment]
Looks good.
