### ISSUE TITLE
Test Case : Orders > part(s) > New Part WIZ - initial part status

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#672]
When a new part is created, the initial status that the part is assigned is "Part Created"

Please change to initial Part Status to "Testing" ( the Part Statuses "Part Created" and "Test Complete" have been removed from the UI workflow )

<img width="1064" alt="screen shot 2017-01-17 at 2 28 43 pm" src="https://cloud.githubusercontent.com/assets/2165796/22040393/af99deec-dcd0-11e6-885e-04aa3c33dc55.png">

**Comment by barryross** [comment]
@leobardoramon Where and when else does the part status change in the workflow?  I'm poking around `admin`

**Comment by barryross** [comment]
In determining how to solve this, I'm trying to determine if there are other pieces/locations that will need to talk to the "status"

**Comment by barryross** [comment]
@leobardoramon never-mind, #670 answered my question

**Comment by barryross** [comment]
This should now be resolved.  Please test on `contractor_barry`

Relevant Commit: 2cea593e7196e7086d0810987eb006e429e597bd

**Comment by leobardoramon** [comment]
Looks good
