### ISSUE TITLE
Orders -> New Order -> Invalid Dimensions "NaN"

### ISSUE THREAD

**Issue by barryross** [codetodesign/NYUAMS#673]
Encountering "NaN' issue when trying to enter dimension sizes in the "wide format" panel.  This does not seem to happen on the New Part panel, only in the context of New Order

<img width="361" alt="screen shot 2017-01-18 at 12 04 14 pm" src="https://cloud.githubusercontent.com/assets/2281667/22080839/f9ccdb40-dd75-11e6-8b71-aeb374ee61b3.png">

**Comment by barryross** [comment]
so, this is a tricky little one.  From what I can tell, the NaN, is the result of the fact that the system cannot find the `width` and `height` of some images.  After testing this out, I see it has nothing to do with whether this is a new part for an existing order, or a new part for a new order.  It actually has to do with whether the file was uploaded my from my local machine or the remote server.  Files  uploaded through the remote server are properly getting processed and the width/height being stored.  Those from my local one are not.  

See below, the left window is output from my local machine for `screent.png` and the right window is output from the remote server for `screent.png`. The left one encounters errors.  Can you please let me know if you are encountering this from your local version as well?

**Comment by barryross** [comment]
<img width="1240" alt="screen shot 2017-01-22 at 11 05 24 am" src="https://cloud.githubusercontent.com/assets/2281667/22185042/c48bb7f6-e092-11e6-8283-5d1f813d71d4.png">

**Comment by barryross** [comment]
This wasn't a bug so much as changes I or others using OSX need to make when running locally.  I have included the local fix in the .readme.  https://github.com/codetodesign/NYUAMS/blob/contractor_barry/troubleshooting/notes.md

**Comment by leobardoramon** [comment]
Cool.  Thank you.
