### ISSUE TITLE
Orders -> Part status panel

### ISSUE THREAD

**Issue by barryross** [codetodesign/NYUAMS#679]
For consistency, I have updated the Part status panel as accessed by the Queue table to the following 

This is an add-on for #670

**Comment by barryross** [comment]
## Accessed through main table
<img width="1357" alt="screen shot 2017-01-20 at 4 10 41 pm" src="https://cloud.githubusercontent.com/assets/2281667/22169667/bf0a78a8-df2a-11e6-9f46-29ac20767f4c.png">

## Accessed through radio selection view

<img width="1376" alt="screen shot 2017-01-20 at 4 10 56 pm" src="https://cloud.githubusercontent.com/assets/2281667/22169666/bf09bd82-df2a-11e6-8325-deaad0a38cf9.png">

**Comment by leobardoramon** [comment]
Beautiful.  Thank you.

**Comment by NYU-AMS** [comment]
looks good to me

**Comment by barryross** [comment]
Excellent, you're welcome!
