### ISSUE TITLE
File proxy server - where should PROD v2 be pulling from?

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#681]
G,

Which GitHub branch should the new PROD environment be pulling code from ?

Is this something that needs to be created?

**Comment by leobardoramon** [comment]
@gosha1128  , I'm assuming that the fileproxy server for PROD would still be pulling from origin "master" 

my question is:

 - do we need to push to Branch "master"?

**Comment by gosha1128** [comment]
Technically you should test on any fix/feature branches like Barry's and
then merge to master and only ever deploy master...

Proxy via master is fine unless Barry is working bugs on that

**Comment by leobardoramon** [comment]
@barryross , we're ready to mount the server locally... can you merge to "master" when you have a moment.  Let us know if you have any questions

**Comment by barryross** [comment]
@leobardoramon just seeing this.  You would like me to merge `contractor_barry` into `master`?

**Comment by barryross** [comment]
I thought there are still more items to test though?

**Comment by leobardoramon** [comment]
The issue is,  we need a server to mount locally,  so that the client can
view/download PDFs - to provide invoices and receipts , they are Vientiane
unable to access this device

**Comment by barryross** [comment]
Okay, I have a couple calls back to back until about 3:45.  When I'm able, you would like me to merge `contractor_barry` with `master` is that correct?

**Comment by leobardoramon** [comment]
Assuming that it is in a Production-ready state,  yes please.

If not, when can toy have that ready?

On Feb 28, 2017 16:52, "Barry Ross" <notifications@github.com> wrote:

Okay, I have a couple calls back to back until about 3:45. When I'm able,
you would like me to merge contractor_barry with master is that correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codetodesign/NYUAMS/issues/681#issuecomment-283172167>,
or mute the thread

**Comment by barryross** [comment]
@leobardoramon I’m a bit confused what I can do to help, b/c a bunch of work on `contractor_barry` is still labeled “ready_for_testing"...so hasn’t been flagged as production-ready yet
