### ISSUE TITLE
Be able to view receipts Orders -> Transactions

### ISSUE THREAD

**Issue by barryross** [codetodesign/NYUAMS#683]
Similar to https://github.com/codetodesign/NYUAMS/issues/486, but ensure we can view receipts in "Open" column when "transactions" radio is selected in "orders"

**Comment by barryross** [comment]
Please test on `contractor_barry`
Relevant Commit: https://github.com/codetodesign/NYUAMS/commit/852fd2c41f9506ad065345dc26d52caeb52eb0c8
Video demo: https://www.dropbox.com/s/7f9b587wfnq40rn/683-receipts-on-orders.mov?dl=0

**Comment by barryross** [comment]
@leobardoramon @gosha1128 I don't feel the need to re-estimate/invoice for this one...it was close to the original scope of what I planned/estimated.  Thank you though.

**Comment by leobardoramon** [comment]
Looks good
