### ISSUE TITLE
fileproxy servers

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#689]
added to Staff Checkout Machine Right - NYUAMS_v2.0
![screen shot 2017-03-01 at 3 32 00 am](https://cloud.githubusercontent.com/assets/2165796/23451899/ede4923e-fe2f-11e6-8bc0-d79baeb1d4cf.png)

**Comment by leobardoramon** [comment]
added to Staff Checkout Machine Left - NYUAMS_v2.0

btw, these are the instructions I'm following:

Fileproxy server
Terminal
If you are working from a new computer, you will need to install Homebrew and Node.js
Clone and Run Local Server
>cd ~
>mkdir fileproxy_server
>cd fileproxy_server
>git clone https://www.github.com/codetodesign/NYUAMS
Barry, please note that these instructions do not take into account that you are working from the branch “contractor_barry”.  Please modify your workflow accordingly. ty
>cd NYUAMS/node/ebs/local
>npm install express
>sudo killall node
enter password
>sudo node fileproxy.js

![screen shot 2017-03-01 at 3 38 53 am](https://cloud.githubusercontent.com/assets/2165796/23452106/f79955a2-fe30-11e6-81cf-f50779b82a6e.png)

**Comment by NYU-AMS** [comment]
We are good on this
