### ISSUE TITLE
MySQL Table Checks - Broken

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#715]
The table Checks is broken in PRODSQL5 

I think that instead of clearing table data ( only ) that the whole table was cleared .

 ... I'm hoping we can copy the same table from QASQL and just replace the broken table 

 ... Otherwise we can restore the DB using a snapshot .

**Comment by leobardoramon** [comment]
fixed

**Comment by leobardoramon** [comment]
This issue is not fixed ...

@barryross , can you please vet this issue ?

1 . Admin/accounts/Bulk Check Generator

2 . after generating bulk checks for a given account , the check "counter" should reset ; this will start the check number back to "1" at the beginning of each school year .

3 . right now , the system is giving us the popup "check already used" ... this is happening after we've created bulk checks

4 . when looking at the table "Checks" in MySQL ... it looks very disorganized . this leads me to believe that something happened with the formatting of the table itself which is causing issues with check numbers .

**Comment by barryross** [comment]
@leobardoramon Hey, I think we pushed a fix for this in early October.  Can you please remind me if this is resolved or if it is still open? Thanks!

**Comment by leobardoramon** [comment]
This is resolved . We reformatted the duplicate Account that was causing crossing data to break the table.

Thank you
