### ISSUE TITLE
Test Case : Orders/Checkout Wizard

### ISSUE THREAD

**Issue by leobardoramon** [codetodesign/NYUAMS#722]
PROD CLONE ENVIRONMENT : 

PROD14 : 52.201.165.160
  pem : prodebs2018-07-09
PRODFILES7 : 54.236.17.119
  pem : prodfiles2018-07-09

TEST SCRIPT : 

   via Terminal 
 - >>node app.js nfs

   via Chrome
   TEST 1

 - Login to database
 - go to Admin/accounts page
 - select a client
 - select Manage Check
 - observe check history : find used check number , find unused check number
 <  eg. "Tisch School of the Arts , Design" ; Rapid Prototype check numbers "417_1" , "417_5" >
 - Go to Orders
 - Select the "checkout" button for a Rapid Prototype order
 - Select "Next" button
 - Select "Split Payment" box
 - Select "Next" button
 - Open "Select Payment Type..."
 - Select "Grant Check"
 - Enter Check Code < 417_1 , 417_5 >
 - Checkout Wizard should say "Check has been used" or "Available Balance : ___" , respectively
 - Checkout Wizard actually says : "Invalid Check ID"

NOTE : this makes me believe that this is not related the the "Admin/accounts" page , but is actually related to the way the Orders page's Checkout wizard is reading the check number

TEST 2

 - Login to database
 - go to Admin/accounts page
 - select a client
 - select Manage Check
 - Go to Rapid Prototype tab
 - Select "Add 10 More Checks"
 - Observe Check ID for new check < 417_41 >
 - Go to Orders
 - Select the "checkout" button for a Rapid Prototype order
 - Select "Next" button
 - Select "Split Payment" box
 - Select "Next" button
 - Open "Select Payment Type..."
 - Select "Grant Check"
 - Enter Check Code < 417_41 >
 - Checkout Wizard should say "Available Balance : ___"
 - Checkout Wizard actually says : "Invalid Check ID"

See video here : https://drive.google.com/open?id=11AgFElp4mS9NUuQ4w1k_yBSsLJNJP4IL

**Comment by leobardoramon** [comment]
@buck0land  , actually , I was entering the wrong check code ... I'll be in tomorrow morning to connect .

I ran two tests : 

I - 
 - (a) attempt check out with used check code ( unsuccesful )  ✔️
 - (b) attempt checkout with new check code ( success ) ✔️
 - (c) bulk check generator with a (1) New Grant Account ( Graduate School of Arts and Science (graduate) , Chemistry, Chemistry, PHD [ 375 ] ) ( success ) ✔️
 - (d) attempt checkout with used check code ( success ) ✔️
See Video Here : 
 - https://drive.google.com/open?id=1YTIV4B1HTqI3pjlUXgPLomP0yGASdPeC
II - 
 - (a) attempt checkout with new check code ( success ) ✔️
 - (b) attempt checkout with used check code  ( unsuccess ) ✔️
 - (c) attempt checkout with new check code ( success ) ✔️
 - (d) bulk check generator with a New Grant Account (2) Existing Grant Account ( Tisch School of the Arts , Design [ 417 ] ) ( success ) ✔️
 - (e) attempt checkout with used check code ( success ) ✔️
See Video Here : 
 - https://drive.google.com/open?id=19EnePRbzxovQIWuiGsn1y_rlKXesiW8N

**Comment by leobardoramon** [comment]
*REFRESH ISSUE*

@barry , the problem what not clear to me , all of the above test scripts are not relevant ,

Please see #723

**Comment by barryross** [comment]
@leobardoramon okay, thanks for the update!
